import { TelemetryEventName, EVENT_NAMES } from "./events";

export interface TelemetryEventCatalogEntry {
  name: TelemetryEventName;
  category: "auth" | "wallet" | "creator" | "marketplace" | "navigation" | "engagement" | "system";
  description: string;
  version: number;
  owner: string;
  status: "active" | "deprecated";
  replacement?: TelemetryEventName;
}

export const TELEMETRY_EVENT_CATALOG: Record<TelemetryEventName, TelemetryEventCatalogEntry> = {
  wallet_connect_modal_closed: {
    name: EVENT_NAMES.walletConnectModalClosed,
    category: "wallet",
    description: "Wallet connect modal closed by user",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_session_rehydrate_started: {
    name: EVENT_NAMES.walletSessionRehydrateStarted,
    category: "wallet",
    description: "Wallet session rehydrate started",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_session_rehydrate_succeeded: {
    name: EVENT_NAMES.walletSessionRehydrateSucceeded,
    category: "wallet",
    description: "Wallet session rehydrate succeeded",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_session_rehydrate_failed: {
    name: EVENT_NAMES.walletSessionRehydrateFailed,
    category: "wallet",
    description: "Wallet session rehydrate failed",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_provider_state_changed: {
    name: EVENT_NAMES.walletProviderStateChanged,
    category: "wallet",
    description: "Wallet provider state changed (account/network)",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_connect_modal_opened: {
    name: EVENT_NAMES.walletConnectModalOpened,
    category: "wallet",
    description: "Wallet connect modal opened by user",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_connect_provider_selected: {
    name: EVENT_NAMES.walletConnectProviderSelected,
    category: "wallet",
    description: "User selected a wallet provider in connect modal",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_connect_submitted: {
    name: EVENT_NAMES.walletConnectSubmitted,
    category: "wallet",
    description: "User submitted wallet connect form",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_connect_succeeded: {
    name: EVENT_NAMES.walletConnectSucceeded,
    category: "wallet",
    description: "Wallet connect succeeded",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_connect_failed: {
    name: EVENT_NAMES.walletConnectFailed,
    category: "wallet",
    description: "Wallet connect failed",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_disconnect_clicked: {
    name: EVENT_NAMES.walletDisconnectClicked,
    category: "wallet",
    description: "User clicked disconnect wallet",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_disconnect_succeeded: {
    name: EVENT_NAMES.walletDisconnectSucceeded,
    category: "wallet",
    description: "Wallet disconnect succeeded",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  wallet_disconnect_failed: {
    name: EVENT_NAMES.walletDisconnectFailed,
    category: "wallet",
    description: "Wallet disconnect failed",
    version: 1,
    owner: "wallet",
    status: "active",
  },
  auth_login_submitted: {
    name: EVENT_NAMES.authLoginSubmitted,
    category: "auth",
    description: "User submitted login form",
    version: 1,
    owner: "auth",
    status: "active",
  },
  auth_login_succeeded: {
    name: EVENT_NAMES.authLoginSucceeded,
    category: "auth",
    description: "User login succeeded",
    version: 1,
    owner: "auth",
    status: "active",
  },
  auth_login_failed: {
    name: EVENT_NAMES.authLoginFailed,
    category: "auth",
    description: "User login failed",
    version: 1,
    owner: "auth",
    status: "active",
  },
  auth_register_submitted: {
    name: EVENT_NAMES.authRegisterSubmitted,
    category: "auth",
    description: "User submitted register form",
    version: 1,
    owner: "auth",
    status: "active",
  },
  auth_register_succeeded: {
    name: EVENT_NAMES.authRegisterSucceeded,
    category: "auth",
    description: "User registration succeeded",
    version: 1,
    owner: "auth",
    status: "active",
  },
  auth_register_failed: {
    name: EVENT_NAMES.authRegisterFailed,
    category: "auth",
    description: "User registration failed",
    version: 1,
    owner: "auth",
    status: "active",
  },
  collection_create_submitted: {
    name: EVENT_NAMES.collectionCreateSubmitted,
    category: "creator",
    description: "User submitted collection creation",
    version: 1,
    owner: "creator",
    status: "active",
  },
  collection_create_succeeded: {
    name: EVENT_NAMES.collectionCreateSucceeded,
    category: "creator",
    description: "Collection creation succeeded",
    version: 1,
    owner: "creator",
    status: "active",
  },
  collection_create_failed: {
    name: EVENT_NAMES.collectionCreateFailed,
    category: "creator",
    description: "Collection creation failed",
    version: 1,
    owner: "creator",
    status: "active",
  },
  mint_nft_submitted: {
    name: EVENT_NAMES.mintNftSubmitted,
    category: "creator",
    description: "User submitted NFT minting",
    version: 1,
    owner: "creator",
    status: "active",
  },
  mint_nft_succeeded: {
    name: EVENT_NAMES.mintNftSucceeded,
    category: "creator",
    description: "NFT minting succeeded",
    version: 1,
    owner: "creator",
    status: "active",
  },
  mint_nft_failed: {
    name: EVENT_NAMES.mintNftFailed,
    category: "creator",
    description: "NFT minting failed",
    version: 1,
    owner: "creator",
    status: "active",
  },
  listing_create_submitted: {
    name: EVENT_NAMES.listingCreateSubmitted,
    category: "creator",
    description: "User submitted listing creation",
    version: 1,
    owner: "creator",
    status: "active",
  },
  listing_create_succeeded: {
    name: EVENT_NAMES.listingCreateSucceeded,
    category: "creator",
    description: "Listing creation succeeded",
    version: 1,
    owner: "creator",
    status: "active",
  },
  listing_create_failed: {
    name: EVENT_NAMES.listingCreateFailed,
    category: "creator",
    description: "Listing creation failed",
    version: 1,
    owner: "creator",
    status: "active",
  },
  cta_clicked: {
    name: EVENT_NAMES.ctaClicked,
    category: "engagement",
    description: "User clicked a call-to-action",
    version: 1,
    owner: "engagement",
    status: "active",
  },
  nav_item_clicked: {
    name: EVENT_NAMES.navItemClicked,
    category: "navigation",
    description: "User clicked a navigation item",
    version: 1,
    owner: "navigation",
    status: "active",
  },
  section_viewed: {
    name: EVENT_NAMES.sectionViewed,
    category: "navigation",
    description: "User viewed a section",
    version: 1,
    owner: "navigation",
    status: "active",
  },
  experiment_exposed: {
    name: EVENT_NAMES.experimentExposed,
    category: "engagement",
    description: "User was exposed to an experiment variant (A/B test)",
    version: 1,
    owner: "growth",
    status: "active",
  },
  experiment_interaction: {
    name: EVENT_NAMES.experimentInteraction,
    category: "engagement",
    description: "User interacted with a CTA or element as part of an experiment variant",
    version: 1,
    owner: "growth",
    status: "active",
  },
  experiment_conversion: {
    name: EVENT_NAMES.experimentConversion,
    category: "engagement",
    description: "User completed a conversion event attributed to an experiment variant",
    version: 1,
    owner: "growth",
    status: "active",
  },
  experiment_assignment_info: {
    name: EVENT_NAMES.experimentAssignmentInfo,
    category: "system",
    description: "Debug event documenting all active experiment assignments for a user/session",
    version: 1,
    owner: "growth",
    status: "active",
  },
  creator_dashboard_error: {
    name: EVENT_NAMES.creatorDashboardError,
    category: "creator",
    description: "Creator dashboard render error event",
    version: 1,
    owner: "creator",
    status: "active",
  },
};
